### ISSUE TITLE
From LaTeX to Asciidoctor

### ISSUE THREAD

**Issue by denkspuren** [denkspuren/consize#3]
Convert LaTeX source to Asciidoctor format for improved online reading in git.

**Comment by Liverm0r** [comment]
Markdown is also good for reading online https://github.com/denkspuren/consize/pull/14

**Comment by denkspuren** [comment]
Thanks a lot! How did you produce the markdown version? Can you think of an automated routine, just in case when I update the `tex` files?

**Comment by Liverm0r** [comment]
I just used [pandoc](https://pandoc.org/installing.html)
`pandoc Consize.tex -s -o md/Consize.md`

**Comment by denkspuren** [comment]
I might continue using LaTeX or change to Quarto instead of Asciidoctor.
