### ISSUE TITLE
Distill minimal dynamic language VM from consize, Factor, Forth,...

### ISSUE THREAD

**Issue by ponyatov** [denkspuren/consize#5]
Is it possible to distill minimal dynamic language VM to make it separate ultra portable project to write pure dynamic object languages like Factor, consize, SmallTalk,... ?

It would be great to have a lot of VM ports to widely used platforms (Android in the first place for me), and some system independent image format (or it can be recompiled for the concrete platform if required).

I've done some experiments with Python here: https://ponyatov.github.io/DLR/
and extra compact fork there (in progress): https://github.com/ponyatov/o
but maybe it will be more progressive to share efforts on porting.

**Comment by denkspuren** [comment]
Sounds interesting. I'll propose your idea to my students -- some of them might enjoy the topic and the idea. The master course on "kernel architectures for programming languages" starts in April.

**Comment by ponyatov** [comment]
Today I found link to book updated: http://www.craftinginterpreters.com/contents.html
Some notes there can be used as a variant on VM implementation.

**Comment by ponyatov** [comment]
Actor model looks great comparing to synchronous call/return in traditional OOP for rising distributed systems.

**Comment by denkspuren** [comment]
Thanks for the link, content looks great!

**Comment by ponyatov** [comment]
It would be great to find some entry level tutorial on making actor-based object system.
Some notes I do here: https://github.com/ponyatov/o/releases/latest

I want to integrate actors and algograph (*), maybe you can advise some intro materials on this theme.

(*) hypergraph made from active objects able to do computations, primarily for AG transformations itself, and it would be great to have code autogenerators able to translate models into executable code in C(++), Java,..

**Comment by denkspuren** [comment]
Thanks for the link to your notes. Sounds interesting!

By the way, do you know Ometa? https://en.m.wikipedia.org/wiki/OMeta
