### ISSUE TITLE
Unexpected behavior of word 'undocument'

### ISSUE THREAD

**Issue by keddelzz** [denkspuren/consize#6]
On my machine the word 'undocument' doesn't work as expected.

### Steps to reproduce

1) Create a file 'Test.txt' with the following content:
```
This is literate documentation.

>> Definition of a word.
>> Definition of another word.

This is more documentation.
```

2) Start the consize repl as described in [Run consize](https://github.com/denkspuren/consize#run-consize) and type in
```
> \ Test.txt slurp undocument
```

### Expected behavior
The top of the stack should be a word, with the content
```
Definition of a word.
Definition of another word.
```

### Actual behavior
On tos is a word, with the content
```
Definition of a word.
```

### Probable fix
Change the relevant [regex in the vm implementation](https://github.com/denkspuren/consize/blob/85527b019fb245ac35e30c9bd7ac9991c3b9b0a4/src/consize.clj#L82) to `#"%?>> (.*)[(\r\n)\r\n]"`.

### Potentially relevant details of my machine
- OS: Linux Mint 18.3 Sylvia
- Clojure Version: 1.9.0, I'm using the installed instead of the slim version.

**Comment by denkspuren** [comment]
Danke an @keddelzz!
